language: node_js
node_js:
  - node # uses most recent stable node version
dist: trusty # uses trusty environment
sudo: false # when on trusty, uses Docker containers for speed
install:
  - npm i -g npm@5.7.1 # delete once 5.7.X is out of "pre-release"
  - npm ci             # faster, goes only from package-lock
